CREATE TABLE IF NOT EXISTS profiles(
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NULL,
  avatar VARCHAR NULL
);

CREATE TABLE IF NOT EXISTS images(
  id SERIAL PRIMARY KEY,
  profile_id INTEGER REFERENCES profiles (id) NOT NULL,
  url VARCHAR NOT NULL
);